"""
Static metadata for the 66 Protestant canon books.
Each book has names in English, Amharic, Oromo, and Tigrigna.
"""

BOOKS = [
    # (number, abbreviation, english_name, testament, chapters, amharic_name, oromo_name, tigrigna_name)
    (1,  "GEN", "Genesis",          "OT", 50,  "ዘፍጥረት",                  "Uumama",              "ዘፍጥረት"),
    (2,  "EXO", "Exodus",           "OT", 40,  "ዘፀዓት",                   "Ba'uu",               "ዘፀጋ"),
    (3,  "LEV", "Leviticus",        "OT", 27,  "ዘሌዋውያን",                 "Leewota",             "ዘሌዋ"),
    (4,  "NUM", "Numbers",          "OT", 36,  "ዘቁጥሮች",                  "Lakkoofsa",           "ዘቁጽሪ"),
    (5,  "DEU", "Deuteronomy",      "OT", 34,  "ዘዳግም",                   "Seera Lammaffaa",     "ዘዳጎም"),
    (6,  "JOS", "Joshua",           "OT", 24,  "ኢያሱ",                    "Yoosuwa",             "ኢያሱ"),
    (7,  "JDG", "Judges",           "OT", 21,  "መሳፍንት",                  "Abbaa Murtiichaa",    "መሳፍንቲ"),
    (8,  "RUT", "Ruth",             "OT",  4,  "ሩት",                     "Ruutii",              "ሩት"),
    (9,  "1SA", "1 Samuel",         "OT", 31,  "፩ሳሙኤል",                  "1ffaa Samueel",       "፩ ሳሙኤል"),
    (10, "2SA", "2 Samuel",         "OT", 24,  "፪ሳሙኤል",                  "2ffaa Samueel",       "፪ ሳሙኤል"),
    (11, "1KI", "1 Kings",          "OT", 22,  "፩ነገሥት",                  "1ffaa Mootota",       "፩ ነገስቲ"),
    (12, "2KI", "2 Kings",          "OT", 25,  "፪ነገሥት",                  "2ffaa Mootota",       "፪ ነገስቲ"),
    (13, "1CH", "1 Chronicles",     "OT", 29,  "፩ዜና ዘዳዊት",              "1ffaa Oduu",          "፩ ዜናሙ"),
    (14, "2CH", "2 Chronicles",     "OT", 36,  "፪ዜና ዘዳዊት",              "2ffaa Oduu",          "፪ ዜናሙ"),
    (15, "EZR", "Ezra",             "OT", 10,  "ዕዝራ",                    "Eeziraa",             "ዕዝራ"),
    (16, "NEH", "Nehemiah",         "OT", 13,  "ነህምያ",                   "Neeheemiyaas",        "ነህምያ"),
    (17, "EST", "Esther",           "OT", 10,  "አስቴር",                   "Asiteeri",            "ኤስቴር"),
    (18, "JOB", "Job",              "OT", 42,  "ኢዮብ",                    "Iyoobi",              "ኢዮብ"),
    (19, "PSA", "Psalms",           "OT", 150, "መዝሙር",                   "Faarfannaa",          "መዝሙር"),
    (20, "PRO", "Proverbs",         "OT", 31,  "ምሳሌ",                    "Mammaaksa",           "ምሳሌ"),
    (21, "ECC", "Ecclesiastes",     "OT", 12,  "መክብብ",                   "Macca Dubbi",         "ምስባክ"),
    (22, "SNG", "Song of Solomon",  "OT",  8,  "መኃልየ መኃልይ ዘሰሎሞን",     "Faaruu",              "ዜማ"),
    (23, "ISA", "Isaiah",           "OT", 66,  "ኢሳይያስ",                  "Isaayyaas",           "ኢሳይያስ"),
    (24, "JER", "Jeremiah",         "OT", 52,  "ኤርምያስ",                  "Irmiyaas",            "ኤርምያስ"),
    (25, "LAM", "Lamentations",     "OT",  5,  "ሰቆቃወ ኤርምያስ",           "Booyichaa",           "ሰቆቃ ኤርምያስ"),
    (26, "EZK", "Ezekiel",          "OT", 48,  "ሕዝቅኤል",                  "Hezqeel",             "ሕዝቅኤል"),
    (27, "DAN", "Daniel",           "OT", 12,  "ዳኒኤል",                   "Daanil",              "ዳኒኤል"),
    (28, "HOS", "Hosea",            "OT", 14,  "ሆሴዕ",                    "Hoshee'a",            "ሆሴዓ"),
    (29, "JOL", "Joel",             "OT",  3,  "ኢዮኤል",                   "Yoo'eel",             "ዮኤል"),
    (30, "AMO", "Amos",             "OT",  9,  "አሞጽ",                    "Aamoos",              "ኣሞጽ"),
    (31, "OBA", "Obadiah",          "OT",  1,  "አብድዮስ",                  "Obadiyaas",           "ኦብድያ"),
    (32, "JON", "Jonah",            "OT",  4,  "ዮናስ",                    "Yoonaas",             "ዮናስ"),
    (33, "MIC", "Micah",            "OT",  7,  "ሚክያስ",                   "Miiqiyaas",           "ሚካ"),
    (34, "NAH", "Nahum",            "OT",  3,  "ናሆም",                    "Naahuumi",            "ናሆም"),
    (35, "HAB", "Habakkuk",         "OT",  3,  "ዕንባቆም",                  "Haabaaquuqi",         "ኣንባቆም"),
    (36, "ZEP", "Zephaniah",        "OT",  3,  "ሶፎንያስ",                  "Sofooniyaas",         "ሶፎንያ"),
    (37, "HAG", "Haggai",           "OT",  2,  "ሐጌ",                     "Haagaai",             "ሓጌ"),
    (38, "ZEC", "Zechariah",        "OT", 14,  "ዘካርያስ",                  "Zaakaariyaas",        "ዘካርያስ"),
    (39, "MAL", "Malachi",          "OT",  4,  "ሚልክያስ",                  "Malaakii",            "ሚልክያ"),
    (40, "MAT", "Matthew",          "NT", 28,  "ማቴዎስ",                   "Matewoos",            "ማቴዎስ"),
    (41, "MRK", "Mark",             "NT", 16,  "ማርቆስ",                   "Maarqoos",            "ማርቆስ"),
    (42, "LUK", "Luke",             "NT", 24,  "ሉቃስ",                    "Luuqaas",             "ሉቃስ"),
    (43, "JHN", "John",             "NT", 21,  "ዮሐንስ",                   "Yoohannis",           "ዮሓንስ"),
    (44, "ACT", "Acts",             "NT", 28,  "ሐዋርያት ሥራ",             "Hojii Ergamootaa",    "ግብሪ ሓዋርያት"),
    (45, "ROM", "Romans",           "NT", 16,  "ሮሜ",                     "Roomaa",              "ሮሜ"),
    (46, "1CO", "1 Corinthians",    "NT", 16,  "፩ቆሮንቶስ",                 "1ffaa Qorontos",      "፩ ቆሮንቶስ"),
    (47, "2CO", "2 Corinthians",    "NT", 13,  "፪ቆሮንቶስ",                 "2ffaa Qorontos",      "፪ ቆሮንቶስ"),
    (48, "GAL", "Galatians",        "NT",  6,  "ገላትያ",                   "Galaatiyaa",          "ገላትያ"),
    (49, "EPH", "Ephesians",        "NT",  6,  "ኤፌሶን",                   "Efeson",              "ኤፌሶን"),
    (50, "PHP", "Philippians",      "NT",  4,  "ፊሊጵስዩስ",                 "Filiphisiyuus",       "ፊሊጵስዩስ"),
    (51, "COL", "Colossians",       "NT",  4,  "ቆላስይስ",                  "Kolossiyoos",         "ቆሎሴ"),
    (52, "1TH", "1 Thessalonians",  "NT",  5,  "፩ተሰሎንቄ",                 "1ffaa Tesaloonikee",  "፩ ተሰሎንቄ"),
    (53, "2TH", "2 Thessalonians",  "NT",  3,  "፪ተሰሎንቄ",                 "2ffaa Tesaloonikee",  "፪ ተሰሎንቄ"),
    (54, "1TI", "1 Timothy",        "NT",  6,  "፩ጢሞቴዎስ",                 "1ffaa Xiimooteewoos", "፩ ጢሞቴዎስ"),
    (55, "2TI", "2 Timothy",        "NT",  4,  "፪ጢሞቴዎስ",                 "2ffaa Xiimooteewoos", "፪ ጢሞቴዎስ"),
    (56, "TIT", "Titus",            "NT",  3,  "ቲቶ",                     "Tiitoos",             "ቲቶ"),
    (57, "PHM", "Philemon",         "NT",  1,  "ፊልሞና",                   "Filiimoon",           "ፊሌሞን"),
    (58, "HEB", "Hebrews",          "NT", 13,  "ዕብራውያን",                 "Ibrootaa",            "ዕብሩያን"),
    (59, "JAS", "James",            "NT",  5,  "ያዕቆብ",                   "Yaaqoob",             "ያዕቆብ"),
    (60, "1PE", "1 Peter",          "NT",  5,  "፩ጴጥሮስ",                  "1ffaa Pheexroos",     "፩ ጴጥሮስ"),
    (61, "2PE", "2 Peter",          "NT",  3,  "፪ጴጥሮስ",                  "2ffaa Pheexroos",     "፪ ጴጥሮስ"),
    (62, "1JN", "1 John",           "NT",  5,  "፩ዮሐንስ",                  "1ffaa Yoohannis",     "፩ ዮሓንስ"),
    (63, "2JN", "2 John",           "NT",  1,  "፪ዮሐንስ",                  "2ffaa Yoohannis",     "፪ ዮሓንስ"),
    (64, "3JN", "3 John",           "NT",  1,  "፫ዮሐንስ",                  "3ffaa Yoohannis",     "፫ ዮሓንስ"),
    (65, "JUD", "Jude",             "NT",  1,  "ይሁዳ",                    "Yuudaa",              "ይሁዳ"),
    (66, "REV", "Revelation",       "NT", 22,  "ራዕይ",                    "Mul'ata",             "ራእይ"),
]

# Alternative name lookups (for passage reference parsing)
BOOK_ALIASES = {
    "gen": "GEN", "genesis": "GEN",
    "exo": "EXO", "exodus": "EXO",
    "lev": "LEV", "leviticus": "LEV",
    "num": "NUM", "numbers": "NUM",
    "deu": "DEU", "deut": "DEU", "deuteronomy": "DEU",
    "jos": "JOS", "josh": "JOS", "joshua": "JOS",
    "jdg": "JDG", "judg": "JDG", "judges": "JDG",
    "rut": "RUT", "ruth": "RUT",
    "1sa": "1SA", "1sam": "1SA", "1 samuel": "1SA",
    "2sa": "2SA", "2sam": "2SA", "2 samuel": "2SA",
    "1ki": "1KI", "1kgs": "1KI", "1 kings": "1KI",
    "2ki": "2KI", "2kgs": "2KI", "2 kings": "2KI",
    "1ch": "1CH", "1chr": "1CH", "1 chronicles": "1CH",
    "2ch": "2CH", "2chr": "2CH", "2 chronicles": "2CH",
    "ezr": "EZR", "ezra": "EZR",
    "neh": "NEH", "nehemiah": "NEH",
    "est": "EST", "esther": "EST",
    "job": "JOB",
    "psa": "PSA", "ps": "PSA", "psalm": "PSA", "psalms": "PSA",
    "pro": "PRO", "prov": "PRO", "proverbs": "PRO",
    "ecc": "ECC", "eccl": "ECC", "ecclesiastes": "ECC",
    "sng": "SNG", "song": "SNG", "ss": "SNG",
    "isa": "ISA", "isaiah": "ISA",
    "jer": "JER", "jeremiah": "JER",
    "lam": "LAM", "lamentations": "LAM",
    "ezk": "EZK", "eze": "EZK", "ezekiel": "EZK",
    "dan": "DAN", "daniel": "DAN",
    "hos": "HOS", "hosea": "HOS",
    "jol": "JOL", "joel": "JOL",
    "amo": "AMO", "amos": "AMO",
    "oba": "OBA", "obadiah": "OBA",
    "jon": "JON", "jonah": "JON",
    "mic": "MIC", "micah": "MIC",
    "nah": "NAH", "nahum": "NAH",
    "hab": "HAB", "habakkuk": "HAB",
    "zep": "ZEP", "zeph": "ZEP", "zephaniah": "ZEP",
    "hag": "HAG", "haggai": "HAG",
    "zec": "ZEC", "zech": "ZEC", "zechariah": "ZEC",
    "mal": "MAL", "malachi": "MAL",
    "mat": "MAT", "matt": "MAT", "matthew": "MAT",
    "mrk": "MRK", "mar": "MRK", "mark": "MRK",
    "luk": "LUK", "luke": "LUK",
    "jhn": "JHN", "jn": "JHN", "john": "JHN",
    "act": "ACT", "acts": "ACT",
    "rom": "ROM", "romans": "ROM",
    "1co": "1CO", "1cor": "1CO", "1 corinthians": "1CO",
    "2co": "2CO", "2cor": "2CO", "2 corinthians": "2CO",
    "gal": "GAL", "galatians": "GAL",
    "eph": "EPH", "ephesians": "EPH",
    "php": "PHP", "phil": "PHP", "philippians": "PHP",
    "col": "COL", "colossians": "COL",
    "1th": "1TH", "1thess": "1TH", "1 thessalonians": "1TH",
    "2th": "2TH", "2thess": "2TH", "2 thessalonians": "2TH",
    "1ti": "1TI", "1tim": "1TI", "1 timothy": "1TI",
    "2ti": "2TI", "2tim": "2TI", "2 timothy": "2TI",
    "tit": "TIT", "titus": "TIT",
    "phm": "PHM", "phlm": "PHM", "philemon": "PHM",
    "heb": "HEB", "hebrews": "HEB",
    "jas": "JAS", "james": "JAS",
    "1pe": "1PE", "1pet": "1PE", "1 peter": "1PE",
    "2pe": "2PE", "2pet": "2PE", "2 peter": "2PE",
    "1jn": "1JN", "1john": "1JN", "1 john": "1JN",
    "2jn": "2JN", "2john": "2JN", "2 john": "2JN",
    "3jn": "3JN", "3john": "3JN", "3 john": "3JN",
    "jud": "JUD", "jude": "JUD",
    "rev": "REV", "revelation": "REV",
}
