"""
Static metadata for the 66 Protestant canon books.
Each book has names in English, Amharic, Oromo, and Tigrigna.

Name sources (all verified against official published translations):
  Amharic  — magna25/amharic-bible-json (wordproject.org / Ethiopian Bible Society)
  Oromo    — YouVersion MacQul v3202 (Bible Society of Ethiopia, 1997)
  Tigrigna — beteZION.com (Eritrean Bible Society / Bible Society of Eritrea)
"""

BOOKS = [
    # (number, abbreviation, english_name, testament, chapters, amharic_name, oromo_name, tigrigna_name)
    (1,  "GEN", "Genesis",          "OT", 50,  "ኦሪት ዘፍጥረት",                        "Seera Uumamaa",                         "ዘፍጥረት"),
    (2,  "EXO", "Exodus",           "OT", 40,  "ኦሪት ዘጸአት",                          "Seera Ba'uu",                           "ዘጸአት"),
    (3,  "LEV", "Leviticus",        "OT", 27,  "ኦሪት ዘሌዋውያን",                        "Seera Lewwootaa",                       "ዘሌዋውያን"),
    (4,  "NUM", "Numbers",          "OT", 36,  "ኦሪት ዘኍልቍ",                          "Seera Lakkoobsaa",                      "ዘሁልቍ"),
    (5,  "DEU", "Deuteronomy",      "OT", 34,  "ኦሪት ዘዳግም",                          "Seera Keessa Deebii",                   "ዘዳግም"),
    (6,  "JOS", "Joshua",           "OT", 24,  "መጽሐፈ ኢያሱ ወልደ ነዌ",                  "Macaafa Iyaasuu",                       "እያሱ"),
    (7,  "JDG", "Judges",           "OT", 21,  "መጽሐፈ መሣፍንት",                        "Macaafa Abboota Firdii",                "መሳፍንቲ"),
    (8,  "RUT", "Ruth",             "OT",  4,  "መጽሐፈ ሩት",                           "Macaafa Ruut",                          "ሩት"),
    (9,  "1SA", "1 Samuel",         "OT", 31,  "መጽሐፈ ሳሙኤል ቀዳማዊ",                   "Macaafa Saamu'el Isa Duraa",            "1ይ ሳሙኤል"),
    (10, "2SA", "2 Samuel",         "OT", 24,  "መጽሐፈ ሳሙኤል ካልዕ",                    "Macaafa Saamu'el Isa Lammaffaa",        "2ይ ሳሙኤል"),
    (11, "1KI", "1 Kings",          "OT", 22,  "መጽሐፈ ነገሥት ቀዳማዊ",                   "Macaafa Moototaa Isa Duraa",            "1ይ ነገስት"),
    (12, "2KI", "2 Kings",          "OT", 25,  "መጽሐፈ ነገሥት ካልዕ",                    "Macaafa Moototaa Isa Lammaffaa",        "2ይ ነገስት"),
    (13, "1CH", "1 Chronicles",     "OT", 29,  "መጽሐፈ ዜና መዋዕል ቀዳማዊ",               "Macaafa Seenaa Baraa Isa Duraa",        "1ይ ዜና መዋእል"),
    (14, "2CH", "2 Chronicles",     "OT", 36,  "መጽሐፈ ዜና መዋዕል ካልዕ",                "Macaafa Seenaa Baraa Isa Lammaffaa",    "2ይ ዜና መዋእል"),
    (15, "EZR", "Ezra",             "OT", 10,  "መጽሐፈ ዕዝራ",                          "Macaafa Izraa",                         "እዝራ"),
    (16, "NEH", "Nehemiah",         "OT", 13,  "መጽሐፈ ነህምያ",                         "Macaafa Nahimiiyaa",                    "ነህምያ"),
    (17, "EST", "Esther",           "OT", 10,  "መጽሐፈ አስቴር",                         "Macaafa Asteer",                        "ኣስቴር"),
    (18, "JOB", "Job",              "OT", 42,  "መጽሐፈ ኢዮብ",                          "Macaafa Iyoob",                         "እዮብ"),
    (19, "PSA", "Psalms",           "OT", 150, "መዝሙረ ዳዊት",                          "Macaafa Faarfannaa",                    "መዝሙር"),
    (20, "PRO", "Proverbs",         "OT", 31,  "መጽሐፈ ምሳሌ",                          "Macaafa Fakkeenyaa",                    "ምሳሌ"),
    (21, "ECC", "Ecclesiastes",     "OT", 12,  "መጽሐፈ መክብብ",                         "Macaafa Lallabaa",                      "መክብብ"),
    (22, "SNG", "Song of Solomon",  "OT",  8,  "መኃልየ መኃልይ ዘሰሎሞን",                  "Macaafa Weedduu Weedduu Caalu",         "መሃልየ መሃልይ"),
    (23, "ISA", "Isaiah",           "OT", 66,  "ትንቢተ ኢሳይያስ",                        "Macaafa Isaayaas Raajichaa",            "ኢሳይያስ"),
    (24, "JER", "Jeremiah",         "OT", 52,  "ትንቢተ ኤርምያስ",                        "Macaafa Ermiyaas Raajichaa",            "ኤርምያስ"),
    (25, "LAM", "Lamentations",     "OT",  5,  "ሰቆቃው ኤርምያስ",                        "Faaruu Ermiyaas",                       "ድጒዓ"),
    (26, "EZK", "Ezekiel",          "OT", 48,  "ትንቢተ ሕዝቅኤል",                        "Macaafa Hisqi'el Raajichaa",            "ህዝቅኤል"),
    (27, "DAN", "Daniel",           "OT", 12,  "ትንቢተ ዳንኤል",                         "Macaafa Daani'el Raajichaa",            "ዳንኤል"),
    (28, "HOS", "Hosea",            "OT", 14,  "ትንቢተ ሆሴዕ",                          "Macaafa Hose'a Raajichaa",              "ሆሴዕ"),
    (29, "JOL", "Joel",             "OT",  3,  "ትንቢተ ኢዮኤል",                         "Macaafa Yo'el Raajichaa",               "ዮኤል"),
    (30, "AMO", "Amos",             "OT",  9,  "ትንቢተ አሞጽ",                          "Macaafa Amos Raajichaa",                "አሞጽ"),
    (31, "OBA", "Obadiah",          "OT",  1,  "ትንቢተ አብድዩ",                         "Macaafa Obaadiiyaa Raajichaa",          "ኦብድያ"),
    (32, "JON", "Jonah",            "OT",  4,  "ትንቢተ ዮናስ",                          "Yoonaas Raajichaa",                     "ዮናስ"),
    (33, "MIC", "Micah",            "OT",  7,  "ትንቢተ ሚክያስ",                         "Macaafa Miikiyaas Raajichaa",           "ሚክያስ"),
    (34, "NAH", "Nahum",            "OT",  3,  "ትንቢተ ናሆም",                          "Macaafa Naahuumi Raajichaa",            "ናሆም"),
    (35, "HAB", "Habakkuk",         "OT",  3,  "ትንቢተ ዕንባቆም",                        "Macaafa Anbaaqom Raajichaa",            "ኣንባቆም"),
    (36, "ZEP", "Zephaniah",        "OT",  3,  "ትንቢተ ሶፎንያስ",                        "Macaafa Sefaaniyaa Raajichaa",          "ጸፎንያስ"),
    (37, "HAG", "Haggai",           "OT",  2,  "ትንቢተ ሐጌ",                           "Macaafa Haagee Raajichaa",              "ሃጌ"),
    (38, "ZEC", "Zechariah",        "OT", 14,  "ትንቢተ ዘካርያስ",                        "Macaafa Zakaariyaas Raajichaa",         "ዘካርያስ"),
    (39, "MAL", "Malachi",          "OT",  4,  "ትንቢተ ሚልክያ",                         "Macaafa Miilkiyaas Raajichaa",          "ሚልክያስ"),
    (40, "MAT", "Matthew",          "NT", 28,  "የማቴዎስ ወንጌል",                        "Wangeela Maatewos",                     "ማቴዎስ"),
    (41, "MRK", "Mark",             "NT", 16,  "የማርቆስ ወንጌል",                        "Wangeela Maarqos",                      "ማርቆስ"),
    (42, "LUK", "Luke",             "NT", 24,  "የሉቃስ ወንጌል",                         "Wangeela Luqaas",                       "ሉቃስ"),
    (43, "JHN", "John",             "NT", 21,  "የዮሐንስ ወንጌል",                        "Wangeela Yohannis",                     "ዮሃንስ"),
    (44, "ACT", "Acts",             "NT", 28,  "የሐዋርያት ሥራ",                         "Hojii Ergamootaa",                      "ግብሪ ሃዋርያት"),
    (45, "ROM", "Romans",           "NT", 16,  "ወደ ሮሜ ሰዎች",                         "Gara Warra Roomaa",                     "ሮሜ"),
    (46, "1CO", "1 Corinthians",    "NT", 16,  "1ኛ ወደ ቆሮንቶስ ሰዎች",                  "1 Gara Warra Qorontos",                 "1ይ ቈረንቶስ"),
    (47, "2CO", "2 Corinthians",    "NT", 13,  "2ኛ ወደ ቆሮንቶስ ሰዎች",                  "2 Gara Warra Qorontos",                 "2ይ ቈረንቶስ"),
    (48, "GAL", "Galatians",        "NT",  6,  "ወደ ገላትያ ሰዎች",                       "Gara Warra Galaatiyaa",                 "ገላትያ"),
    (49, "EPH", "Ephesians",        "NT",  6,  "ወደ ኤፌሶን ሰዎች",                       "Gara Warra Efesoon",                    "ኤፌሶን"),
    (50, "PHP", "Philippians",      "NT",  4,  "ወደ ፊልጵስዩስ ሰዎች",                    "Gara Warra Filiphisiiyus",              "ፊልጲ"),
    (51, "COL", "Colossians",       "NT",  4,  "ወደ ቆላስይስ ሰዎች",                      "Gara Warra Qolosaayis",                 "ቈሎሴ"),
    (52, "1TH", "1 Thessalonians",  "NT",  5,  "1ኛ ወደ ተሰሎንቄ ሰዎች",                  "1 Gara Warra Tasaloniiqee",             "1ይ ተሰሎንቄ"),
    (53, "2TH", "2 Thessalonians",  "NT",  3,  "2ኛ ወደ ተሰሎንቄ ሰዎች",                  "2 Gara Warra Tasaloniiqee",             "2ይ ተሰሎንቄ"),
    (54, "1TI", "1 Timothy",        "NT",  6,  "1ኛ ወደ ጢሞቴዎስ",                       "1 Gara Thimotewos",                     "1ይ ጢሞቴዎስ"),
    (55, "2TI", "2 Timothy",        "NT",  4,  "2ኛ ወደ ጢሞቴዎስ",                       "2 Gara Thimotewos",                     "2ይ ጢሞቴዎስ"),
    (56, "TIT", "Titus",            "NT",  3,  "ወደ ቲቶ",                              "Gara Tiitoos",                          "ቲቶስ"),
    (57, "PHM", "Philemon",         "NT",  1,  "ወደ ፊልሞና",                            "Gara Filemon",                          "ፊልሞን"),
    (58, "HEB", "Hebrews",          "NT", 13,  "ወደ ዕብራውያን",                         "Gara Ibrootaa",                         "እብራውያን"),
    (59, "JAS", "James",            "NT",  5,  "የያዕቆብ መልእክት",                       "Ergaa Yaaqoob",                         "ያእቆብ"),
    (60, "1PE", "1 Peter",          "NT",  5,  "1ኛ የጴጥሮስ መልእክት",                    "1 Ergaa Phethros",                      "1ይ ጴጥሮስ"),
    (61, "2PE", "2 Peter",          "NT",  3,  "2ኛ የጴጥሮስ መልእክት",                    "2 Ergaa Phethros",                      "2ይ ጴጥሮስ"),
    (62, "1JN", "1 John",           "NT",  5,  "1ኛ የዮሐንስ መልእክት",                    "1 Ergaa Yohannis",                      "1ይ ዮሃንስ"),
    (63, "2JN", "2 John",           "NT",  1,  "2ኛ የዮሐንስ መልእክት",                    "2 Ergaa Yohannis",                      "2ይ ዮሃንስ"),
    (64, "3JN", "3 John",           "NT",  1,  "3ኛ የዮሐንስ መልእክት",                    "3 Ergaa Yohannis",                      "3ይ ዮሃንስ"),
    (65, "JUD", "Jude",             "NT",  1,  "የይሁዳ መልእክት",                        "Ergaa Yihudaa",                         "ይሁዳ"),
    (66, "REV", "Revelation",       "NT", 22,  "የዮሐንስ ራዕይ",                         "Mul'ata Yohannis",                      "ራእይ"),
]

# Alternative name lookups (for passage reference parsing)
BOOK_ALIASES = {
    "gen": "GEN", "genesis": "GEN",
    "exo": "EXO", "exodus": "EXO",
    "lev": "LEV", "leviticus": "LEV",
    "num": "NUM", "numbers": "NUM",
    "deu": "DEU", "deut": "DEU", "deuteronomy": "DEU",
    "jos": "JOS", "josh": "JOS", "joshua": "JOS",
    "jdg": "JDG", "judg": "JDG", "judges": "JDG",
    "rut": "RUT", "ruth": "RUT",
    "1sa": "1SA", "1sam": "1SA", "1 samuel": "1SA",
    "2sa": "2SA", "2sam": "2SA", "2 samuel": "2SA",
    "1ki": "1KI", "1kgs": "1KI", "1 kings": "1KI",
    "2ki": "2KI", "2kgs": "2KI", "2 kings": "2KI",
    "1ch": "1CH", "1chr": "1CH", "1 chronicles": "1CH",
    "2ch": "2CH", "2chr": "2CH", "2 chronicles": "2CH",
    "ezr": "EZR", "ezra": "EZR",
    "neh": "NEH", "nehemiah": "NEH",
    "est": "EST", "esther": "EST",
    "job": "JOB",
    "psa": "PSA", "ps": "PSA", "psalm": "PSA", "psalms": "PSA",
    "pro": "PRO", "prov": "PRO", "proverbs": "PRO",
    "ecc": "ECC", "eccl": "ECC", "ecclesiastes": "ECC",
    "sng": "SNG", "song": "SNG", "ss": "SNG", "sos": "SNG",
    "isa": "ISA", "isaiah": "ISA",
    "jer": "JER", "jeremiah": "JER",
    "lam": "LAM", "lamentations": "LAM",
    "ezk": "EZK", "ezek": "EZK", "ezekiel": "EZK",
    "dan": "DAN", "daniel": "DAN",
    "hos": "HOS", "hosea": "HOS",
    "jol": "JOL", "joel": "JOL",
    "amo": "AMO", "amos": "AMO",
    "oba": "OBA", "obadiah": "OBA",
    "jon": "JON", "jonah": "JON",
    "mic": "MIC", "micah": "MIC",
    "nah": "NAH", "nahum": "NAH",
    "hab": "HAB", "habakkuk": "HAB",
    "zep": "ZEP", "zeph": "ZEP", "zephaniah": "ZEP",
    "hag": "HAG", "haggai": "HAG",
    "zec": "ZEC", "zech": "ZEC", "zechariah": "ZEC",
    "mal": "MAL", "malachi": "MAL",
    "mat": "MAT", "matt": "MAT", "matthew": "MAT",
    "mrk": "MRK", "mark": "MRK",
    "luk": "LUK", "luke": "LUK",
    "jhn": "JHN", "john": "JHN",
    "act": "ACT", "acts": "ACT",
    "rom": "ROM", "romans": "ROM",
    "1co": "1CO", "1cor": "1CO", "1 corinthians": "1CO",
    "2co": "2CO", "2cor": "2CO", "2 corinthians": "2CO",
    "gal": "GAL", "galatians": "GAL",
    "eph": "EPH", "ephesians": "EPH",
    "php": "PHP", "phil": "PHP", "philippians": "PHP",
    "col": "COL", "colossians": "COL",
    "1th": "1TH", "1thes": "1TH", "1 thessalonians": "1TH",
    "2th": "2TH", "2thes": "2TH", "2 thessalonians": "2TH",
    "1ti": "1TI", "1tim": "1TI", "1 timothy": "1TI",
    "2ti": "2TI", "2tim": "2TI", "2 timothy": "2TI",
    "tit": "TIT", "titus": "TIT",
    "phm": "PHM", "philemon": "PHM",
    "heb": "HEB", "hebrews": "HEB",
    "jas": "JAS", "james": "JAS",
    "1pe": "1PE", "1pet": "1PE", "1 peter": "1PE",
    "2pe": "2PE", "2pet": "2PE", "2 peter": "2PE",
    "1jn": "1JN", "1john": "1JN", "1 john": "1JN",
    "2jn": "2JN", "2john": "2JN", "2 john": "2JN",
    "3jn": "3JN", "3john": "3JN", "3 john": "3JN",
    "jud": "JUD", "jude": "JUD",
    "rev": "REV", "revelation": "REV", "revelations": "REV",
}
