"""
Static metadata for the 66 Protestant canon books.
Each book has names in English, Amharic, Oromo, and Tigrigna.

Name sources (all verified against official published translations):
  Amharic  — YouVersion NASV v1260 (አዲሱ መደበኛ ትርጒም, Biblica / Bible Society of Ethiopia)
  Oromo    — YouVersion MacQul v3202 (Bible Society of Ethiopia, 1997)
  Tigrigna — beteZION.com (Bible Society of Eritrea)
"""

BOOKS = [
    # (number, abbreviation, english_name, testament, chapters, amharic_name, oromo_name, tigrigna_name)
    (1,  "GEN", "Genesis",          "OT", 50,  "ዘፍጥረት",               "Seera Uumamaa",                      "ዘፍጥረት"),
    (2,  "EXO", "Exodus",           "OT", 40,  "ዘፀአት",                "Seera Ba'uu",                        "ዘጸአት"),
    (3,  "LEV", "Leviticus",        "OT", 27,  "ዘሌዋውያን",              "Seera Lewwootaa",                    "ዘሌዋውያን"),
    (4,  "NUM", "Numbers",          "OT", 36,  "ዘኍልቍ",                "Seera Lakkoobsaa",                   "ዘሁልቍ"),
    (5,  "DEU", "Deuteronomy",      "OT", 34,  "ዘዳግም",                "Seera Keessa Deebii",                "ዘዳግም"),
    (6,  "JOS", "Joshua",           "OT", 24,  "ኢያሱ",                 "Macaafa Iyaasuu",                    "እያሱ"),
    (7,  "JDG", "Judges",           "OT", 21,  "መሳፍንት",               "Macaafa Abboota Firdii",             "መሳፍንቲ"),
    (8,  "RUT", "Ruth",             "OT",  4,  "ሩት",                  "Macaafa Ruut",                       "ሩት"),
    (9,  "1SA", "1 Samuel",         "OT", 31,  "1 ሳሙኤል",              "Macaafa Saamu'el Isa Duraa",         "1ይ ሳሙኤል"),
    (10, "2SA", "2 Samuel",         "OT", 24,  "2 ሳሙኤል",              "Macaafa Saamu'el Isa Lammaffaa",     "2ይ ሳሙኤል"),
    (11, "1KI", "1 Kings",          "OT", 22,  "1 ነገሥት",              "Macaafa Moototaa Isa Duraa",         "1ይ ነገስት"),
    (12, "2KI", "2 Kings",          "OT", 25,  "2 ነገሥት",              "Macaafa Moototaa Isa Lammaffaa",     "2ይ ነገስት"),
    (13, "1CH", "1 Chronicles",     "OT", 29,  "1 ዜና መዋዕል",           "Macaafa Seenaa Baraa Isa Duraa",     "1ይ ዜና መዋእል"),
    (14, "2CH", "2 Chronicles",     "OT", 36,  "2 ዜና መዋዕል",           "Macaafa Seenaa Baraa Isa Lammaffaa", "2ይ ዜና መዋእል"),
    (15, "EZR", "Ezra",             "OT", 10,  "ዕዝራ",                 "Macaafa Izraa",                      "እዝራ"),
    (16, "NEH", "Nehemiah",         "OT", 13,  "ነህምያ",                "Macaafa Nahimiiyaa",                 "ነህምያ"),
    (17, "EST", "Esther",           "OT", 10,  "አስቴር",                "Macaafa Asteer",                     "ኣስቴር"),
    (18, "JOB", "Job",              "OT", 42,  "ኢዮብ",                 "Macaafa Iyoob",                      "እዮብ"),
    (19, "PSA", "Psalms",           "OT", 150, "መዝሙር",                "Macaafa Faarfannaa",                 "መዝሙር"),
    (20, "PRO", "Proverbs",         "OT", 31,  "ምሳሌ",                 "Macaafa Fakkeenyaa",                 "ምሳሌ"),
    (21, "ECC", "Ecclesiastes",     "OT", 12,  "መክብብ",                "Macaafa Lallabaa",                   "መክብብ"),
    (22, "SNG", "Song of Solomon",  "OT",  8,  "ማሕልየ መሓልይ",          "Macaafa Weedduu Weedduu Caalu",      "መሃልየ መሃልይ"),
    (23, "ISA", "Isaiah",           "OT", 66,  "ኢሳይያስ",               "Macaafa Isaayaas Raajichaa",         "ኢሳይያስ"),
    (24, "JER", "Jeremiah",         "OT", 52,  "ኤርምያስ",               "Macaafa Ermiyaas Raajichaa",         "ኤርምያስ"),
    (25, "LAM", "Lamentations",     "OT",  5,  "ሰቈቃወ",                "Faaruu Ermiyaas",                    "ድጒዓ"),
    (26, "EZK", "Ezekiel",          "OT", 48,  "ሕዝቅኤል",               "Macaafa Hisqi'el Raajichaa",         "ህዝቅኤል"),
    (27, "DAN", "Daniel",           "OT", 12,  "ዳንኤል",                "Macaafa Daani'el Raajichaa",         "ዳንኤል"),
    (28, "HOS", "Hosea",            "OT", 14,  "ሆሴዕ",                 "Macaafa Hose'a Raajichaa",           "ሆሴዕ"),
    (29, "JOL", "Joel",             "OT",  3,  "ኢዩኤል",                "Macaafa Yo'el Raajichaa",            "ዮኤል"),
    (30, "AMO", "Amos",             "OT",  9,  "አሞጽ",                 "Macaafa Amos Raajichaa",             "አሞጽ"),
    (31, "OBA", "Obadiah",          "OT",  1,  "አብድዩ",                "Macaafa Obaadiiyaa Raajichaa",       "ኦብድያ"),
    (32, "JON", "Jonah",            "OT",  4,  "ዮናስ",                 "Yoonaas Raajichaa",                  "ዮናስ"),
    (33, "MIC", "Micah",            "OT",  7,  "ሚክያስ",                "Macaafa Miikiyaas Raajichaa",        "ሚክያስ"),
    (34, "NAH", "Nahum",            "OT",  3,  "ናሆም",                 "Macaafa Naahuumi Raajichaa",         "ናሆም"),
    (35, "HAB", "Habakkuk",         "OT",  3,  "ዕንባቆም",               "Macaafa Anbaaqom Raajichaa",         "ኣንባቆም"),
    (36, "ZEP", "Zephaniah",        "OT",  3,  "ሶፎንያስ",               "Macaafa Sefaaniyaa Raajichaa",       "ጸፎንያስ"),
    (37, "HAG", "Haggai",           "OT",  2,  "ሐጌ",                  "Macaafa Haagee Raajichaa",           "ሃጌ"),
    (38, "ZEC", "Zechariah",        "OT", 14,  "ዘካርያስ",               "Macaafa Zakaariyaas Raajichaa",      "ዘካርያስ"),
    (39, "MAL", "Malachi",          "OT",  4,  "ሚልክያስ",               "Macaafa Miilkiyaas Raajichaa",       "ሚልክያስ"),
    (40, "MAT", "Matthew",          "NT", 28,  "ማቴዎስ",                "Wangeela Maatewos",                  "ማቴዎስ"),
    (41, "MRK", "Mark",             "NT", 16,  "ማርቆስ",                "Wangeela Maarqos",                   "ማርቆስ"),
    (42, "LUK", "Luke",             "NT", 24,  "ሉቃስ",                 "Wangeela Luqaas",                    "ሉቃስ"),
    (43, "JHN", "John",             "NT", 21,  "ዮሐንስ",                "Wangeela Yohannis",                  "ዮሃንስ"),
    (44, "ACT", "Acts",             "NT", 28,  "ሐዋርያት ሥራ",            "Hojii Ergamootaa",                   "ግብሪ ሃዋርያት"),
    (45, "ROM", "Romans",           "NT", 16,  "ሮሜ",                  "Gara Warra Roomaa",                  "ሮሜ"),
    (46, "1CO", "1 Corinthians",    "NT", 16,  "1 ቆሮንቶስ",             "1 Gara Warra Qorontos",              "1ይ ቈረንቶስ"),
    (47, "2CO", "2 Corinthians",    "NT", 13,  "2 ቆሮንቶስ",             "2 Gara Warra Qorontos",              "2ይ ቈረንቶስ"),
    (48, "GAL", "Galatians",        "NT",  6,  "ገላትያ",                "Gara Warra Galaatiyaa",              "ገላትያ"),
    (49, "EPH", "Ephesians",        "NT",  6,  "ኤፌሶን",                "Gara Warra Efesoon",                 "ኤፌሶን"),
    (50, "PHP", "Philippians",      "NT",  4,  "ፊልጵስዩስ",              "Gara Warra Filiphisiiyus",           "ፊልጲ"),
    (51, "COL", "Colossians",       "NT",  4,  "ቈላስይስ",               "Gara Warra Qolosaayis",              "ቈሎሴ"),
    (52, "1TH", "1 Thessalonians",  "NT",  5,  "1 ተሰሎንቄ",             "1 Gara Warra Tasaloniiqee",          "1ይ ተሰሎንቄ"),
    (53, "2TH", "2 Thessalonians",  "NT",  3,  "2 ተሰሎንቄ",             "2 Gara Warra Tasaloniiqee",          "2ይ ተሰሎንቄ"),
    (54, "1TI", "1 Timothy",        "NT",  6,  "1 ጢሞቴዎስ",             "1 Gara Thimotewos",                  "1ይ ጢሞቴዎስ"),
    (55, "2TI", "2 Timothy",        "NT",  4,  "2 ጢሞቴዎስ",             "2 Gara Thimotewos",                  "2ይ ጢሞቴዎስ"),
    (56, "TIT", "Titus",            "NT",  3,  "ቲቶ",                  "Gara Tiitoos",                       "ቲቶስ"),
    (57, "PHM", "Philemon",         "NT",  1,  "ፊልሞና",                "Gara Filemon",                       "ፊልሞን"),
    (58, "HEB", "Hebrews",          "NT", 13,  "ዕብራውያን",              "Gara Ibrootaa",                      "እብራውያን"),
    (59, "JAS", "James",            "NT",  5,  "ያዕቆብ",                "Ergaa Yaaqoob",                      "ያእቆብ"),
    (60, "1PE", "1 Peter",          "NT",  5,  "1 ጴጥሮስ",              "1 Ergaa Phethros",                   "1ይ ጴጥሮስ"),
    (61, "2PE", "2 Peter",          "NT",  3,  "2 ጴጥሮስ",              "2 Ergaa Phethros",                   "2ይ ጴጥሮስ"),
    (62, "1JN", "1 John",           "NT",  5,  "1 ዮሐንስ",              "1 Ergaa Yohannis",                   "1ይ ዮሃንስ"),
    (63, "2JN", "2 John",           "NT",  1,  "2 ዮሐንስ",              "2 Ergaa Yohannis",                   "2ይ ዮሃንስ"),
    (64, "3JN", "3 John",           "NT",  1,  "3 ዮሐንስ",              "3 Ergaa Yohannis",                   "3ይ ዮሃንስ"),
    (65, "JUD", "Jude",             "NT",  1,  "ይሁዳ",                 "Ergaa Yihudaa",                      "ይሁዳ"),
    (66, "REV", "Revelation",       "NT", 22,  "ራእይ",                 "Mul'ata Yohannis",                   "ራእይ"),
]

# Alternative name lookups (for passage reference parsing)
BOOK_ALIASES = {
    "gen": "GEN", "genesis": "GEN",
    "exo": "EXO", "exodus": "EXO",
    "lev": "LEV", "leviticus": "LEV",
    "num": "NUM", "numbers": "NUM",
    "deu": "DEU", "deut": "DEU", "deuteronomy": "DEU",
    "jos": "JOS", "josh": "JOS", "joshua": "JOS",
    "jdg": "JDG", "judg": "JDG", "judges": "JDG",
    "rut": "RUT", "ruth": "RUT",
    "1sa": "1SA", "1sam": "1SA", "1 samuel": "1SA",
    "2sa": "2SA", "2sam": "2SA", "2 samuel": "2SA",
    "1ki": "1KI", "1kgs": "1KI", "1 kings": "1KI",
    "2ki": "2KI", "2kgs": "2KI", "2 kings": "2KI",
    "1ch": "1CH", "1chr": "1CH", "1 chronicles": "1CH",
    "2ch": "2CH", "2chr": "2CH", "2 chronicles": "2CH",
    "ezr": "EZR", "ezra": "EZR",
    "neh": "NEH", "nehemiah": "NEH",
    "est": "EST", "esther": "EST",
    "job": "JOB",
    "psa": "PSA", "ps": "PSA", "psalm": "PSA", "psalms": "PSA",
    "pro": "PRO", "prov": "PRO", "proverbs": "PRO",
    "ecc": "ECC", "eccl": "ECC", "ecclesiastes": "ECC",
    "sng": "SNG", "song": "SNG", "ss": "SNG", "sos": "SNG",
    "isa": "ISA", "isaiah": "ISA",
    "jer": "JER", "jeremiah": "JER",
    "lam": "LAM", "lamentations": "LAM",
    "ezk": "EZK", "ezek": "EZK", "ezekiel": "EZK",
    "dan": "DAN", "daniel": "DAN",
    "hos": "HOS", "hosea": "HOS",
    "jol": "JOL", "joel": "JOL",
    "amo": "AMO", "amos": "AMO",
    "oba": "OBA", "obadiah": "OBA",
    "jon": "JON", "jonah": "JON",
    "mic": "MIC", "micah": "MIC",
    "nah": "NAH", "nahum": "NAH",
    "hab": "HAB", "habakkuk": "HAB",
    "zep": "ZEP", "zeph": "ZEP", "zephaniah": "ZEP",
    "hag": "HAG", "haggai": "HAG",
    "zec": "ZEC", "zech": "ZEC", "zechariah": "ZEC",
    "mal": "MAL", "malachi": "MAL",
    "mat": "MAT", "matt": "MAT", "matthew": "MAT",
    "mrk": "MRK", "mark": "MRK",
    "luk": "LUK", "luke": "LUK",
    "jhn": "JHN", "john": "JHN",
    "act": "ACT", "acts": "ACT",
    "rom": "ROM", "romans": "ROM",
    "1co": "1CO", "1cor": "1CO", "1 corinthians": "1CO",
    "2co": "2CO", "2cor": "2CO", "2 corinthians": "2CO",
    "gal": "GAL", "galatians": "GAL",
    "eph": "EPH", "ephesians": "EPH",
    "php": "PHP", "phil": "PHP", "philippians": "PHP",
    "col": "COL", "colossians": "COL",
    "1th": "1TH", "1thes": "1TH", "1 thessalonians": "1TH",
    "2th": "2TH", "2thes": "2TH", "2 thessalonians": "2TH",
    "1ti": "1TI", "1tim": "1TI", "1 timothy": "1TI",
    "2ti": "2TI", "2tim": "2TI", "2 timothy": "2TI",
    "tit": "TIT", "titus": "TIT",
    "phm": "PHM", "philemon": "PHM",
    "heb": "HEB", "hebrews": "HEB",
    "jas": "JAS", "james": "JAS",
    "1pe": "1PE", "1pet": "1PE", "1 peter": "1PE",
    "2pe": "2PE", "2pet": "2PE", "2 peter": "2PE",
    "1jn": "1JN", "1john": "1JN", "1 john": "1JN",
    "2jn": "2JN", "2john": "2JN", "2 john": "2JN",
    "3jn": "3JN", "3john": "3JN", "3 john": "3JN",
    "jud": "JUD", "jude": "JUD",
    "rev": "REV", "revelation": "REV", "revelations": "REV",
}
